### ISSUE TITLE
Error: pc-user-import.py: 400 Client Error: Bad Request for url: https://api.prismacloud.io/user

### ISSUE THREAD

**Issue by john-lowry** [jdrieger/pc-toolbox#9]
Attempting to import a number of users via a csv file and it looks like there is some client issues. Double checked my username and password (API Keys) to confirm they are correct as well as the tenant I am on.

```
ython pc-user-import.py ~/pc-users.csv <removed for security's sake>

Ready to execute commands against your Prisma Cloud tenant.
Would you like to continue (y or yes to continue)?y

API - Getting authentication token...Done.
API - Getting current user list...Traceback (most recent call last):
  File "pc-user-import.py", line 47, in <module>
    pc_settings, response_package = pc_lib_api.api_user_list_get(pc_settings)
  File "/Users/r630850/src/python/pc-toolbox/pc_lib_api.py", line 240, in api_user_list_get
    return pc_call_api(action, url, pc_settings)
  File "/Users/r630850/src/python/pc-toolbox/pc_lib_api.py", line 41, in pc_call_api
    response.raise_for_status()
  File "/Users/r630850/Library/Python/2.7/lib/python/site-packages/requests/models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://api.prismacloud.io/user
```

**Comment by jdrieger** [comment]
The V1 API for users has been disabled on the APP stack and I was unaware.  Updated the user import to now use the V2 API for the GET list.  Re-check out and try again.  This version appears to work on all stacks now.  Also updated the CSV imported to a read only model which should help with CSV compatibility.

Let me know if this works for you.

**Comment by john-lowry** [comment]
Different error now, but I think it fixed the original error. Now getting:

```python pc-user-import.py ~/pc-users.csv <removed for security> 

Ready to execute commands against your Prisma Cloud tenant.
Would you like to continue (y or yes to continue)?y

API - Getting authentication token...Done.
API - Getting current user list...Done.
File - Loading CSV user data...Done.
API - Getting user roles...Done.
Searching for role name to get role ID...Done.
Formatting imported user list and checking for duplicates by e-mail...Traceback (most recent call last):
  File "pc-user-import.py", line 87, in <module>
    if user_new['email'].lower() == user_old['email'].lower():
KeyError: 'email'
```

**Comment by jdrieger** [comment]
I put a template of the CSV in the templates folder.  You need email, firstName, and lastName as the header of the CSV file so it knows what to put where.

**Comment by john-lowry** [comment]
Yep, it is setup that way, still bumping into the error.

```
email,firstName,lastName
john.lowry@domain.com, John, Lowry
```

**Comment by jdrieger** [comment]
Hmmm...  That exact file works for me...  Interesting.  I have no idea why that is not working.  The only difference is Python 2 vs 3.  Do you have a Python 3 test machine anywhere?

**Comment by jdrieger** [comment]
or can you send me your test CSV (the actual file)?  (Encoding perhaps?)

**Comment by john-lowry** [comment]
Yeah, I have used both python2 and python3. Same error message.

Let me check the encoding. I can't share my csv file, it is work product and contains people's email addresses.

**Comment by jdrieger** [comment]
Can you create a copy and delete everything except line 1, and change the name/domain for like 2 entries?  I can test it on my machines as well to see if I can reproduce.  May be able to work out what is happening.

**Comment by john-lowry** [comment]
```
$ file -I ~/pc-users.csv 
pc-users.csv: text/plain; charset=utf-8
$ file -I ~/pc-user-test.csv 
pc-user-test.csv: text/plain; charset=us-ascii
```
I hand generated the pc-user-test.csv file with exactly one user in it. Both of them get the same error.

**Comment by jdrieger** [comment]
What OS are you using?  OSX or Linux?  (I am on Windows ATM but I can try it on whatever OS to see if there is a difference)

**Comment by john-lowry** [comment]
OS X.

**Comment by jdrieger** [comment]
Give me an hour and I will see if I can reproduce.

**Comment by jdrieger** [comment]
For Ubuntu:
ubuntu@host:~/pc-toolbox$ python3 pc-user-import.py ./test-user-import.csv "System Admin"

Ready to execute commands against your Prisma Cloud tenant.
Would you like to continue (y or yes to continue)?y

API - Getting authentication token...Done.
API - Getting current user list...Done.
File - Loading CSV user data...Done.
API - Getting user roles...Done.
Searching for role name to get role ID...Done.
Formatting imported user list and checking for duplicates by e-mail...Done.
Users to add: 2
Users skipped (Duplicates): 1
Users removed as duplicates from CSV: 0
API - Adding users...
Adding user email: <e-mail in CSV>
Adding user email: <e-mail in CSV>
Done.

Encoding:
ubuntu@host:~/pc-toolbox$ file -i ./test-user-import.csv
./test-user-import.csv: text/plain; charset=us-ascii

Attached my test file as well.

Going to test on OSX next to see if I can find out what is happening with your import.

[test-user-import.zip](https://github.com/jdrieger/pc-toolbox/files/6193429/test-user-import.zip)

**Comment by jdrieger** [comment]
For OSX:
$ python3 pc-user-import.py ./test-user-import.csv "System Admin"

Ready to execute commands against your Prisma Cloud tenant.
Would you like to continue (y or yes to continue)?y

API - Getting authentication token...Done.
API - Getting current user list...Done.
File - Loading CSV user data...Done.
API - Getting user roles...Done.
Searching for role name to get role ID...Done.
Formatting imported user list and checking for duplicates by e-mail...Done.
Users to add: 1
Users skipped (Duplicates): 1
Users removed as duplicates from CSV: 0
API - Adding users...
Adding user email: 
Done.

Used the same file copied over.

$ file -I ./test-user-import.csv 
./test-user-import.csv: text/plain; charset=us-ascii

Can you try downloading my test file and seeing if there is some kind of difference?  I have no idea why it would throw that error for you.

**Comment by jdrieger** [comment]
To expand on what it is doing:

The file is being loaded into a python dictionary via the csv library.  It uses the first line to determine the "keys" for the dict.  Then loads the data into the dict.  One of those keys from the first line is "email" (no caps).  Then it compares the "email" key in each record from the API pull to the "email" key from the file load to make sure there are no duplicates.  If there are duplicates, it drops them from the import before moving on.

For some reason, it seems when the file is loaded for yours, it is not loading the "email" key correctly, so when it looks for that key, it cannot find it and errors out.  But the file example you sent is structured correctly, so I have no idea why it is not importing correctly.

If the file example above fails, I can modify the code to add a debug that will dump out the imported JSON and we can see what it is actually getting for yours.

**Comment by john-lowry** [comment]
Sorry about dropping off, Dad and work duties took me away. Changed up the code to print what is going on under the hood a bit. The user it is stopping at is a pre-existing user and in my csv file. But this is what is happening:

```
Formatting imported user list and checking for duplicates by e-mail...
old user
john.lowry@domain.com

new user
Traceback (most recent call last):
  File "pc-user-import.py", line 92, in <module>
    print(user_new['email'])
KeyError: 'email'
```

snippet:
```
for user_old in user_list_old:
              print()
              print("old user")
              print(user_old['email'])
              print()
              print("new user")
              print(user_new['email'])
              if user_new['email'].lower() == user_old['email'].lower():
                  users_skipped_count = users_skipped_count + 1
                  user_exists = True
                  break
```

**Comment by john-lowry** [comment]
Wait, scratch that. I removed the old user from the import list and tweaked code a bit now I get this:
```
python pc-user-import.py ~/pc-users.csv prisma_healthplancombo

Ready to execute commands against your Prisma Cloud tenant.
Would you like to continue (y or yes to continue)?y

API - Getting authentication token...Done.
API - Getting current user list...Done.
File - Loading CSV user data...Done.
API - Getting user roles...Done.
Searching for role name to get role ID...Done.
Formatting imported user list and checking for duplicates by e-mail...
old user
andy@domain.com

new user
{'lastName': 'Smith', 'firstName': 'John', '\xef\xbb\xbfemail': 'john.smith@domain.com'}
Traceback (most recent call last):
  File "pc-user-import.py", line 93, in <module>
    if user_new['email'].lower() == user_old['email'].lower():
KeyError: 'email'
```

The `'\xef\xbb\xbfemail'` is telling there.

**Comment by jdrieger** [comment]
That's interesting.  So it was the data it imported and a misleading error.  Once you delete that record, did it progress properly?

**Comment by john-lowry** [comment]
No, I am stilling getting:

```
\xef\xbb\xbfemail'
```

I got this list as an excel spreadsheet, exported it as a CSV and added my own headers. There has to be some weird encoding thing happening. My headers are literally "email,firstName,lastName" yet it is showing that error.

**Comment by jdrieger** [comment]
it is...:
https://stackoverflow.com/questions/18664712/split-function-add-xef-xbb-xbf-n-to-my-list

There is the header (hidden) in there that is getting imported with the first key (email).  That encoding needs to be removed.  that article gives a method.  You could also likely copy-paste the data into a "clean" shell, and that might solve it also.

**Comment by john-lowry** [comment]
Yep, just came across the same article. Removed the BOM and utility is running. Thanks for sticking with me on this.

**Comment by jdrieger** [comment]
Excellent!  Let me know if you run into any other issues.
